baseurl: ""
url: "https://ttyb.github.io"
# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
encoding: utf-8
permalink: /:categories/:title.html
gems: [jekyll-paginate]

paginate: 8
paginate_path: "page:num"
