baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ttyb.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
encoding: utf-8
permalink: /:categories/:title.html
paginate: 5
paginate_path: "page:num"
gems: [jekyll-paginate]